server {
  listen 80;
  listen [::]:80;
  server_name wallet.pepepow.net;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name wallet.pepepow.net;

  ssl_certificate /etc/letsencrypt/live/wallet.pepepow.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/wallet.pepepow.net/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  root /var/www/pepepow-wallet;
  index index.html;

  location = /healthz {
    proxy_pass http://127.0.0.1:9194;
  }

  location = /readyz {
    proxy_pass http://127.0.0.1:9194;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
